### ISSUE TITLE
--dry-run doesn't work

### ISSUE THREAD

**Issue by lmf-mx** [codingtony/s3-recursive-acl#1]
I've tried running with --dry-run both from the released binary and one built today.
No "DR:" prefix ends up in the output and the ACLs are set.

**Comment by codingtony** [comment]
I was able to reproduce the issue. I have fixed the issue in the last commit. 
Can you confirm the resolution and close if it resolved the issue ?

Thanks! 

P.S. I will put a new release in a few minutes

**Comment by lmf-mx** [comment]
Pulled and built. Work as it should. Thanks!
