### ISSUE TITLE
SlowDown - Please reduce your request rate.

### ISSUE THREAD

**Issue by TheNamesJF** [codingtony/s3-recursive-acl#2]
S3 returns a 503 error message:
2020/01/30 18:47:57 Failed to read acl on s3_key_file, SlowDown: Please reduce your request rate.
        status code: 503, request id: D2166EB6F92DB63D, host id: +fYKkmjrs2G2HA2RZd/595Ff99oTkG7NTfRsFdFXx0f0AiIFrmjVJcxfZUd6iO2cUiCzHz6SQnw=

real    0m48.892s
user    6m43.776s
sys     0m50.653s

and it doesn't exit gracefully. (no report generated)
context: large bucket containing > 4.9M keys

Trying parallel 32 (instead of default 512)

**Comment by codingtony** [comment]
Latest release does report the error in a more graceful way.
Did it work well with 32 ?

Alternatively I could provide a way to specify the amount of request allowed per second.

**Comment by codingtony** [comment]
Default is now 16
